/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 vert3x-drone.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Vert3xDrone(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/vert3x-drone.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="RootNode0" scale={0.01}>
          <group name="geo89" />
          <group name="skeletal1">
            <primitive object={nodes.Root2} />
            <skinnedMesh name="battery102" geometry={nodes.battery102.geometry} material={materials.Material_12} skeleton={nodes.battery102.skeleton} />
            <skinnedMesh name="battery_input101" geometry={nodes.battery_input101.geometry} material={materials.Material_11} skeleton={nodes.battery_input101.skeleton} />
            <skinnedMesh name="big_plate_screw_fittings104" geometry={nodes.big_plate_screw_fittings104.geometry} material={materials.Material_14} skeleton={nodes.big_plate_screw_fittings104.skeleton} />
            <skinnedMesh name="bottom_frame103" geometry={nodes.bottom_frame103.geometry} material={materials.Material_13} skeleton={nodes.bottom_frame103.skeleton} />
            <skinnedMesh name="bottom_venting112" geometry={nodes.bottom_venting112.geometry} material={materials.Material_22} skeleton={nodes.bottom_venting112.skeleton} />
            <group name="camera119">
              <skinnedMesh name="Mesh_29" geometry={nodes.Mesh_29.geometry} material={materials.Material_36} skeleton={nodes.Mesh_29.skeleton} />
              <skinnedMesh name="Mesh_29_1" geometry={nodes.Mesh_29_1.geometry} material={materials['Material.001']} skeleton={nodes.Mesh_29_1.skeleton} />
            </group>
            <group name="camera_base114">
              <skinnedMesh name="Mesh_24" geometry={nodes.Mesh_24.geometry} material={materials.Material_24} skeleton={nodes.Mesh_24.skeleton} />
              <skinnedMesh name="Mesh_24_1" geometry={nodes.Mesh_24_1.geometry} material={materials['Material.001']} skeleton={nodes.Mesh_24_1.skeleton} />
            </group>
            <skinnedMesh name="camera_fitting_screw_1115" geometry={nodes.camera_fitting_screw_1115.geometry} material={materials.Material_25} skeleton={nodes.camera_fitting_screw_1115.skeleton} />
            <skinnedMesh name="camera_fitting_screw_2116" geometry={nodes.camera_fitting_screw_2116.geometry} material={materials.Material_26} skeleton={nodes.camera_fitting_screw_2116.skeleton} />
            <skinnedMesh name="camera_fitting_screw_3117" geometry={nodes.camera_fitting_screw_3117.geometry} material={materials.Material_27} skeleton={nodes.camera_fitting_screw_3117.skeleton} />
            <skinnedMesh name="camera_fitting_screw_4118" geometry={nodes.camera_fitting_screw_4118.geometry} material={materials.Material_28} skeleton={nodes.camera_fitting_screw_4118.skeleton} />
            <skinnedMesh name="camera_screw_1120" geometry={nodes.camera_screw_1120.geometry} material={materials.Material_30} skeleton={nodes.camera_screw_1120.skeleton} />
            <skinnedMesh name="camera_screw_2121" geometry={nodes.camera_screw_2121.geometry} material={materials.Material_31} skeleton={nodes.camera_screw_2121.skeleton} />
            <skinnedMesh name="camera_screw_3122" geometry={nodes.camera_screw_3122.geometry} material={materials.Material_32} skeleton={nodes.camera_screw_3122.skeleton} />
            <group name="leg_1123">
              <skinnedMesh name="Mesh_33" geometry={nodes.Mesh_33.geometry} material={materials.Material_33} skeleton={nodes.Mesh_33.skeleton} />
              <skinnedMesh name="Mesh_33_1" geometry={nodes.Mesh_33_1.geometry} material={materials['Material.001']} skeleton={nodes.Mesh_33_1.skeleton} />
            </group>
            <group name="leg_2124">
              <skinnedMesh name="Mesh_34" geometry={nodes.Mesh_34.geometry} material={materials.Material_34} skeleton={nodes.Mesh_34.skeleton} />
              <skinnedMesh name="Mesh_34_1" geometry={nodes.Mesh_34_1.geometry} material={materials['Material.001']} skeleton={nodes.Mesh_34_1.skeleton} />
            </group>
            <group name="leg_3125">
              <skinnedMesh name="Mesh_35" geometry={nodes.Mesh_35.geometry} material={materials.Material_35} skeleton={nodes.Mesh_35.skeleton} />
              <skinnedMesh name="Mesh_35_1" geometry={nodes.Mesh_35_1.geometry} material={materials['Material.001']} skeleton={nodes.Mesh_35_1.skeleton} />
            </group>
            <group name="leg_4126">
              <skinnedMesh name="Mesh_36" geometry={nodes.Mesh_36.geometry} material={materials.Material_36} skeleton={nodes.Mesh_36.skeleton} />
              <skinnedMesh name="Mesh_36_1" geometry={nodes.Mesh_36_1.geometry} material={materials['Material.001']} skeleton={nodes.Mesh_36_1.skeleton} />
            </group>
            <group name="lower_body111">
              <skinnedMesh name="Mesh_21" geometry={nodes.Mesh_21.geometry} material={materials['Material.002']} skeleton={nodes.Mesh_21.skeleton} />
              <skinnedMesh name="Mesh_21_1" geometry={nodes.Mesh_21_1.geometry} material={materials['Material.001']} skeleton={nodes.Mesh_21_1.skeleton} />
            </group>
            <skinnedMesh name="middle_screw_1105" geometry={nodes.middle_screw_1105.geometry} material={materials.Material_15} skeleton={nodes.middle_screw_1105.skeleton} />
            <skinnedMesh name="middle_screw_2106" geometry={nodes.middle_screw_2106.geometry} material={materials.Material_16} skeleton={nodes.middle_screw_2106.skeleton} />
            <skinnedMesh name="middle_screw_3107" geometry={nodes.middle_screw_3107.geometry} material={materials.Material_17} skeleton={nodes.middle_screw_3107.skeleton} />
            <skinnedMesh name="middle_screw_4108" geometry={nodes.middle_screw_4108.geometry} material={materials.Material_18} skeleton={nodes.middle_screw_4108.skeleton} />
            <skinnedMesh name="middle_screw_5109" geometry={nodes.middle_screw_5109.geometry} material={materials.Material_19} skeleton={nodes.middle_screw_5109.skeleton} />
            <skinnedMesh name="middle_screw_6110" geometry={nodes.middle_screw_6110.geometry} material={materials.Material_20} skeleton={nodes.middle_screw_6110.skeleton} />
            <skinnedMesh name="motor_1129" geometry={nodes.motor_1129.geometry} material={materials.Material_39} skeleton={nodes.motor_1129.skeleton} />
            <skinnedMesh name="motor_2132" geometry={nodes.motor_2132.geometry} material={materials.Material_42} skeleton={nodes.motor_2132.skeleton} />
            <skinnedMesh name="motor_3135" geometry={nodes.motor_3135.geometry} material={materials.Material_45} skeleton={nodes.motor_3135.skeleton} />
            <skinnedMesh name="motor_4138" geometry={nodes.motor_4138.geometry} material={materials.Material_48} skeleton={nodes.motor_4138.skeleton} />
            <skinnedMesh name="motor_base_screw_a_1151" geometry={nodes.motor_base_screw_a_1151.geometry} material={materials.Material_61} skeleton={nodes.motor_base_screw_a_1151.skeleton} />
            <skinnedMesh name="motor_base_screw_a_2152" geometry={nodes.motor_base_screw_a_2152.geometry} material={materials.Material_62} skeleton={nodes.motor_base_screw_a_2152.skeleton} />
            <skinnedMesh name="motor_base_screw_a_3153" geometry={nodes.motor_base_screw_a_3153.geometry} material={materials.Material_63} skeleton={nodes.motor_base_screw_a_3153.skeleton} />
            <skinnedMesh name="motor_base_screw_a_4154" geometry={nodes.motor_base_screw_a_4154.geometry} material={materials.Material_64} skeleton={nodes.motor_base_screw_a_4154.skeleton} />
            <skinnedMesh name="motor_base_screw_b_1155" geometry={nodes.motor_base_screw_b_1155.geometry} material={materials.Material_65} skeleton={nodes.motor_base_screw_b_1155.skeleton} />
            <skinnedMesh name="motor_base_screw_b_2156" geometry={nodes.motor_base_screw_b_2156.geometry} material={materials.Material_66} skeleton={nodes.motor_base_screw_b_2156.skeleton} />
            <skinnedMesh name="motor_base_screw_b_3157" geometry={nodes.motor_base_screw_b_3157.geometry} material={materials.Material_67} skeleton={nodes.motor_base_screw_b_3157.skeleton} />
            <skinnedMesh name="motor_base_screw_b_4158" geometry={nodes.motor_base_screw_b_4158.geometry} material={materials.Material_68} skeleton={nodes.motor_base_screw_b_4158.skeleton} />
            <skinnedMesh name="motor_base_screw_c_1159" geometry={nodes.motor_base_screw_c_1159.geometry} material={materials.Material_69} skeleton={nodes.motor_base_screw_c_1159.skeleton} />
            <skinnedMesh name="motor_base_screw_c_2160" geometry={nodes.motor_base_screw_c_2160.geometry} material={materials.Material_70} skeleton={nodes.motor_base_screw_c_2160.skeleton} />
            <skinnedMesh name="motor_base_screw_c_3161" geometry={nodes.motor_base_screw_c_3161.geometry} material={materials.Material_71} skeleton={nodes.motor_base_screw_c_3161.skeleton} />
            <skinnedMesh name="motor_base_screw_c_4162" geometry={nodes.motor_base_screw_c_4162.geometry} material={materials.Material_72} skeleton={nodes.motor_base_screw_c_4162.skeleton} />
            <skinnedMesh name="motor_base_screw_d_1163" geometry={nodes.motor_base_screw_d_1163.geometry} material={materials.Material_73} skeleton={nodes.motor_base_screw_d_1163.skeleton} />
            <skinnedMesh name="motor_base_screw_d_2164" geometry={nodes.motor_base_screw_d_2164.geometry} material={materials.Material_74} skeleton={nodes.motor_base_screw_d_2164.skeleton} />
            <skinnedMesh name="motor_base_screw_d_3165" geometry={nodes.motor_base_screw_d_3165.geometry} material={materials.Material_75} skeleton={nodes.motor_base_screw_d_3165.skeleton} />
            <skinnedMesh name="motor_base_screw_d_4166" geometry={nodes.motor_base_screw_d_4166.geometry} material={materials.Material_76} skeleton={nodes.motor_base_screw_d_4166.skeleton} />
            <skinnedMesh name="prop_1127" geometry={nodes.prop_1127.geometry} material={materials.Material_37} skeleton={nodes.prop_1127.skeleton} />
            <skinnedMesh name="prop_2130" geometry={nodes.prop_2130.geometry} material={materials.Material_40} skeleton={nodes.prop_2130.skeleton} />
            <skinnedMesh name="prop_3133" geometry={nodes.prop_3133.geometry} material={materials.Material_43} skeleton={nodes.prop_3133.skeleton} />
            <skinnedMesh name="prop_4136" geometry={nodes.prop_4136.geometry} material={materials.Material_46} skeleton={nodes.prop_4136.skeleton} />
            <skinnedMesh name="prop_bolt_cap_1143" geometry={nodes.prop_bolt_cap_1143.geometry} material={materials['Material.001']} skeleton={nodes.prop_bolt_cap_1143.skeleton} />
            <skinnedMesh name="prop_bolt_cap_2144" geometry={nodes.prop_bolt_cap_2144.geometry} material={materials['Material.001']} skeleton={nodes.prop_bolt_cap_2144.skeleton} />
            <skinnedMesh name="prop_bolt_cap_3145" geometry={nodes.prop_bolt_cap_3145.geometry} material={materials['Material.001']} skeleton={nodes.prop_bolt_cap_3145.skeleton} />
            <skinnedMesh name="prop_bolt_cap_4146" geometry={nodes.prop_bolt_cap_4146.geometry} material={materials['Material.001']} skeleton={nodes.prop_bolt_cap_4146.skeleton} />
            <skinnedMesh name="prop_bolt_nut_1139" geometry={nodes.prop_bolt_nut_1139.geometry} material={materials.Material_49} skeleton={nodes.prop_bolt_nut_1139.skeleton} />
            <skinnedMesh name="prop_bolt_nut_2140" geometry={nodes.prop_bolt_nut_2140.geometry} material={materials.Material_50} skeleton={nodes.prop_bolt_nut_2140.skeleton} />
            <skinnedMesh name="prop_bolt_nut_3141" geometry={nodes.prop_bolt_nut_3141.geometry} material={materials.Material_51} skeleton={nodes.prop_bolt_nut_3141.skeleton} />
            <skinnedMesh name="prop_bolt_nut_4142" geometry={nodes.prop_bolt_nut_4142.geometry} material={materials.Material_52} skeleton={nodes.prop_bolt_nut_4142.skeleton} />
            <skinnedMesh name="prop_motor_base_1147" geometry={nodes.prop_motor_base_1147.geometry} material={materials.Material_57} skeleton={nodes.prop_motor_base_1147.skeleton} />
            <skinnedMesh name="prop_motor_base_2148" geometry={nodes.prop_motor_base_2148.geometry} material={materials.Material_58} skeleton={nodes.prop_motor_base_2148.skeleton} />
            <skinnedMesh name="prop_motor_base_3149" geometry={nodes.prop_motor_base_3149.geometry} material={materials.Material_59} skeleton={nodes.prop_motor_base_3149.skeleton} />
            <skinnedMesh name="prop_motor_base_4150" geometry={nodes.prop_motor_base_4150.geometry} material={materials.Material_60} skeleton={nodes.prop_motor_base_4150.skeleton} />
            <skinnedMesh name="prop_motor_bolt_1128" geometry={nodes.prop_motor_bolt_1128.geometry} material={materials.Material_38} skeleton={nodes.prop_motor_bolt_1128.skeleton} />
            <skinnedMesh name="prop_motor_bolt_2131" geometry={nodes.prop_motor_bolt_2131.geometry} material={materials.Material_41} skeleton={nodes.prop_motor_bolt_2131.skeleton} />
            <skinnedMesh name="prop_motor_bolt_3134" geometry={nodes.prop_motor_bolt_3134.geometry} material={materials.Material_44} skeleton={nodes.prop_motor_bolt_3134.skeleton} />
            <skinnedMesh name="prop_motor_bolt_4137" geometry={nodes.prop_motor_bolt_4137.geometry} material={materials.Material_47} skeleton={nodes.prop_motor_bolt_4137.skeleton} />
            <skinnedMesh name="receiver100" geometry={nodes.receiver100.geometry} material={materials.Material_10} skeleton={nodes.receiver100.skeleton} />
            <skinnedMesh name="receiver_input99" geometry={nodes.receiver_input99.geometry} material={materials.Material_9} skeleton={nodes.receiver_input99.skeleton} />
            <skinnedMesh name="receiver_middle_board98" geometry={nodes.receiver_middle_board98.geometry} material={materials.Material_8} skeleton={nodes.receiver_middle_board98.skeleton} />
            <skinnedMesh name="screw_194" geometry={nodes.screw_194.geometry} material={materials.Material_4} skeleton={nodes.screw_194.skeleton} />
            <skinnedMesh name="screw_295" geometry={nodes.screw_295.geometry} material={materials.Material_5} skeleton={nodes.screw_295.skeleton} />
            <skinnedMesh name="screw_396" geometry={nodes.screw_396.geometry} material={materials.Material_6} skeleton={nodes.screw_396.skeleton} />
            <skinnedMesh name="screw_497" geometry={nodes.screw_497.geometry} material={materials.Material_7} skeleton={nodes.screw_497.skeleton} />
            <skinnedMesh name="small_part_plate_190" geometry={nodes.small_part_plate_190.geometry} material={materials['Material_0.002']} skeleton={nodes.small_part_plate_190.skeleton} />
            <skinnedMesh name="small_part_plate_292" geometry={nodes.small_part_plate_292.geometry} material={materials.Material_2} skeleton={nodes.small_part_plate_292.skeleton} />
            <skinnedMesh name="small_part_scew_fittings91" geometry={nodes.small_part_scew_fittings91.geometry} material={materials.Material_1} skeleton={nodes.small_part_scew_fittings91.skeleton} />
            <skinnedMesh name="top_board93" geometry={nodes.top_board93.geometry} material={materials.Material_3} skeleton={nodes.top_board93.skeleton} />
            <group name="upper_body113">
              <skinnedMesh name="Mesh_23" geometry={nodes.Mesh_23.geometry} material={materials.Material_23} skeleton={nodes.Mesh_23.skeleton} />
              <skinnedMesh name="Mesh_23_1" geometry={nodes.Mesh_23_1.geometry} material={materials['Material.002']} skeleton={nodes.Mesh_23_1.skeleton} />
            </group>
          </group>
        </group>
        <group name="RootNode001" scale={0.01}>
          <group name="skeletal002">
            <primitive object={nodes.Root2_1} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/vert3x-drone.glb')
